[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taipy_gui_ext_library"
version = "1.0.0"
authors = [ { name = "Your Name", email = "your@email.domain" } ]
description = "A Taipy GUI extension library."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
keywords = [ "taipy" ]
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
    "Intended Audience :: Developers",
    # "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [ "taipy-gui>=4.0" ]
